from matrimony.view.homepage import home
from matrimony.view.auth import signupview,loginview,signout,signup2
from matrimony.view.feedback import feedbacks
from matrimony.view.membership import membership
from matrimony.view.success import success
from matrimony.view.search import search
from matrimony.view.contact import contact
from matrimony.view.myprofile import myprofile,profile
from matrimony.view.signals import create_profile,save_profile
from matrimony.view.data import dataview
from matrimony.view.profileinfo import profileinfo
from matrimony.view.kyc import kyc
from matrimony.view.qualification import qualification,physical_attribute,photo_album,family_details,horoscope,personal_info,habits