from matrimony.model.feedback import Feedback
from matrimony.model.myprofile import Profile
from matrimony.model.personalinfo import PersonalInfo
from matrimony.model.physicalattribute import PhysicalAttribute
from matrimony.model.qualification import Qualification
from matrimony.model.habit import Habit
from matrimony.model.horoscope import Horoscope
from matrimony.model.familydetails import FamilyDetails
from matrimony.model.photoalbum import PhotoAlbum
from matrimony.model.kyc import Kyc 