# Generated by Django 4.0 on 2022-01-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='description',
        ),
    ]
