# Generated by Django 4.0 on 2022-01-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('matrimony', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('employed_in', models.CharField(max_length=50)),
                ('annual_income', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=50)),
                ('physical_status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='photo1.jpg', upload_to='photo_album')),
                ('image2', models.ImageField(default='photo2.jpg', upload_to='photo_album')),
                ('image3', models.ImageField(default='photo3.jpg', upload_to='photo_album')),
                ('image4', models.ImageField(default='photo4.jpg', upload_to='photo_album')),
                ('image5', models.ImageField(default='photo5.jpg', upload_to='photo_album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhaar_number', models.CharField(max_length=20)),
                ('adhaar_front', models.ImageField(default='front.jpg', upload_to='kyc')),
                ('adhaar_back', models.ImageField(default='back.jpg', upload_to='kyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosh', models.CharField(max_length=50, null=True)),
                ('star', models.CharField(max_length=50, null=True)),
                ('raasi', models.CharField(max_length=50, null=True)),
                ('birth_time', models.CharField(max_length=50, null=True)),
                ('birth_place', models.CharField(max_length=50, null=True)),
                ('kundli', models.ImageField(default='sample.jpg', upload_to='horoscope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=50)),
                ('drinking', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(max_length=50)),
                ('family_type', models.CharField(max_length=50)),
                ('family_value', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('brothers', models.CharField(max_length=50)),
                ('sisters', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
