# Generated by Django 2.1 on 2021-12-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_auto_20211228_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
