# Generated by Django 2.1 on 2021-12-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_customer_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='checkbox',
        ),
    ]
