# Generated by Django 2.1 on 2022-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_remove_customer_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='language',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='religion',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
