# Generated by Django 4.0 on 2022-01-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/matrimony/profile_pics/sample.jpg', upload_to='static/matrimony/profile_pics'),
        ),
    ]
