# Generated by Django 2.1 on 2022-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_auto_20220103_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
