# Generated by Django 4.0 on 2022-01-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0007_auto_20220103_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('no_of_children', models.CharField(max_length=10)),
                ('child_status', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('sub_caste', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
    ]
