# Generated by Django 4.0 on 2022-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='kundli',
            field=models.ImageField(default='sample.jpg', null=True, upload_to='horoscope'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='adhaar_back',
            field=models.ImageField(default='back.jpg', null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='adhaar_front',
            field=models.ImageField(default='front.jpg', null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
