# Generated by Django 4.0 on 2022-01-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0008_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('complexion', models.CharField(max_length=20)),
                ('physical_status', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosh', models.CharField(max_length=20)),
                ('star', models.CharField(max_length=20)),
                ('raasi', models.CharField(max_length=20)),
                ('birth_time', models.TimeField(max_length=20)),
                ('birth_place', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=20)),
                ('smoking', models.CharField(max_length=20)),
                ('drinking', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(max_length=20)),
                ('family_type', models.CharField(max_length=20)),
                ('family_value', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(max_length=20)),
                ('brother', models.CharField(max_length=20)),
                ('married_brother', models.CharField(max_length=20)),
                ('sister', models.CharField(max_length=20)),
                ('married_sister', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=20)),
                ('additional_degree', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('employedin', models.CharField(max_length=20)),
                ('annual_income', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.customer')),
            ],
        ),
    ]
